create table MAT_PRO	(
				nom_mat		varchar2(35),
				nom_pro		varchar2(50),
				CONSTRAINT Cp_MAT_PRO	PRIMARY KEY (nom_mat,nom_pro),
				CONSTRAINT Ca_MAT_PRO_MATERIA	FOREIGN KEY (nom_mat) REFERENCES MATERIA (nom_mat),
				CONSTRAINT Ca_MAT_PRO_PROYECYO	FOREIGN KEY (nom_pro) REFERENCES PROYECTO (nom_pro)
				ON DELETE CASCADE
			)
/
insert into MAT_PRO values ('AGRICULTURA ECOLOGICA', 'AGRICULTURA ECOBIO');
insert into MAT_PRO values ('AGRICULTURA BIOLOGICA', 'AGRICULTURA ECOBIO');
insert into MAT_PRO values ('AGRICULTURA ECOLOGICA', 'REGADIO ECOBIO');
insert into MAT_PRO values ('AGRICULTURA BIOLOGICA', 'REGADIO ECOBIO');
insert into MAT_PRO values ('AGRICULTURA ECOLOGICA', 'SECANO ECOBIO');
insert into MAT_PRO values ('AGRICULTURA BIOLOGICA', 'SECANO ECOBIO');
insert into MAT_PRO values ('GENETICA AGRICOLA', 'AGRICULTURA TRANSGENICA');
insert into MAT_PRO values ('GENETICA AGRICOLA', 'TECNOLOGIA APLICADA AL MUNDO NATURAL');
insert into MAT_PRO values ('GENETICA AGRICOLA', 'TECNOLOGIA APLICADA AL MEDIO RURAL');
insert into MAT_PRO values ('PISCICULTURA ECOLOGICA', 'PISCICULTURA ECOBIO');
insert into MAT_PRO values ('PISCICULTURA BIOLOGICA', 'PISCICULTURA ECOBIO');
insert into MAT_PRO values ('PISCICULTURA ECOLOGICA', 'PISCICULTURA TERCER MUNDO');
insert into MAT_PRO values ('PISCICULTURA BIOLOGICA', 'PISCICULTURA TERCER MUNDO');
insert into MAT_PRO values ('GENETICA PISCICOLA', 'PISCICULTURA TRANSGENICA');
insert into MAT_PRO values ('GENETICA PISCICOLA', 'TECNOLOGIA APLICADA AL MUNDO NATURAL');
insert into MAT_PRO values ('GANADERIA ECOLOGICA', 'GANADERIA ECOBIO');
insert into MAT_PRO values ('GANADERIA BIOLOGICA', 'GANADERIA ECOBIO');
insert into MAT_PRO values ('GANADERIA ECOLOGICA', 'GANADERIA TERCER MUNDO');
insert into MAT_PRO values ('GANADERIA BIOLOGICA', 'GANADERIA TERCER MUNDO');
insert into MAT_PRO values ('GENETICA GANADERA', 'GANADERIA TRANSGENICA');
insert into MAT_PRO values ('GENETICA GANADERA', 'TECNOLOGIA APLICADA AL MUNDO NATURAL');
insert into MAT_PRO values ('GENETICA GANADERA', 'TECNOLOGIA APLICADA AL MEDIO RURAL');
insert into MAT_PRO values ('TECNOLOGIA Y TERCER MUNDO', 'TECNOLOGIA APLICADA EN EL TERCER MUNDO');
insert into MAT_PRO values ('TECNOLOGIA Y DESARROLLO', 'TECNOLOGIA APLICADA EN EL TERCER MUNDO');
insert into MAT_PRO values ('TECNOLOGIA Y TERCER MUNDO', 'TECNOLOGIA APLICADA EN PAISES EN DESARROLLO');
insert into MAT_PRO values ('TECNOLOGIA Y DESARROLLO', 'TECNOLOGIA APLICADA EN PAISES EN DESARROLLO');
insert into MAT_PRO values ('INFORMATICA Y TERCER MUNDO', 'INFORMATICA EN PAISES EN DESARROLLO');
insert into MAT_PRO values ('INFORMATICA Y DESARROLLO', 'INFORMATICA EN PAISES EN DESARROLLO');
insert into MAT_PRO values ('INFORMATICA Y TERCER MUNDO', 'INFORMATICA EN EL TERCER MUNDO');
insert into MAT_PRO values ('INFORMATICA Y DESARROLLO', 'INFORMATICA EN EL TERCER MUNDO');
insert into MAT_PRO values ('INFORMATICA Y DESARROLLO', 'INFORMATICA EN ENTORNOS RURALES');
insert into MAT_PRO values ('IA Y AGRICULTURA', 'INTELIGENCIA ARTIFICIAL APLICADA EN AGRICULTURA');
insert into MAT_PRO values ('IA Y AGRICULTURA', 'INTELIGENCIA ARTIFICIAL EN ENTORNOS RURALES');
insert into MAT_PRO values ('REGADIO ECOLOGICO', 'REGADIO ECOBIO');
insert into MAT_PRO values ('REGADIO BIOLOGICO', 'REGADIO ECOBIO');
insert into MAT_PRO values ('REGADIO ECOLOGICO', 'AGRICULTURA ECOBIO');
insert into MAT_PRO values ('REGADIO BIOLOGICO', 'AGRICULTURA ECOBIO');
insert into MAT_PRO values ('REGADIO ECOLOGICO', 'TECNOLOGIA APLICADA AL MEDIO RURAL');
insert into MAT_PRO values ('REGADIO BIOLOGICO', 'TECNOLOGIA APLICADA AL MEDIO RURAL');
