create table MATERIA_NO_ESPECIAL	(
						nom_mat		varchar2(35),
						ambito		varchar2(15),
						categoria	varchar2(20),
						CONSTRAINT Cp_MATERIA_NO_ESPECIAL PRIMARY KEY (nom_mat),
						CONSTRAINT CF_MATERIA_NO_ESPECIAL FOREIGN KEY (nom_mat) REFERENCES MATERIA(nom_mat)	
						ON DELETE CASCADE
					)
/
insert into MATERIA_NO_ESPECIAL values ('AGRICULTURA BIOLOGICA', 'MUNDIAL', 'MUNDO NATURAL');
insert into MATERIA_NO_ESPECIAL values ('PISCICULTURA BIOLOGICA', 'EUROPEO', 'MUNDO NATURAL');
insert into MATERIA_NO_ESPECIAL values ('GANADERIA BIOLOGICA', 'MUNDIAL', 'MUNDO NATURAL');
insert into MATERIA_NO_ESPECIAL values ('TECNOLOGIA Y DESARROLLO', 'MUNDIAL', 'NUEVAS TECNOLOGIAS');
insert into MATERIA_NO_ESPECIAL values ('INFORMATICA Y DESARROLLO', 'EUROPEO', 'NUEVAS TECNOLOGIAS');
insert into MATERIA_NO_ESPECIAL values ('REGADIO BIOLOGICO', 'REGIONAL', 'MUNDO NATURAL');